
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: arkweid
  password: qwertyror

development:
  <<: *default
  database: guild_master_development

test:
  <<: *default
  database: guild_master_test
